
const GET_POKEMON_LIST = 'GET_POKEMON_LIST';
const GET_POKEMON_LIST_PENDING = 'GET_POKEMON_LIST_PENDING';
const GET_POKEMON_LIST_REJECTED = 'GET_POKEMON_LIST_REJECTED';
const GET_POKEMON_LIST_FULFILLED ='GET_POKEMON_LIST_FULFILLED';

const GET_POKEMON = 'GET_POKEMON';
const GET_POKEMON_PENDING = 'GET_POKEMON_PENDING';
const GET_POKEMON_REJECTED = 'GET_POKEMON_REJECTED';
const GET_POKEMON_FULFILLED ='GET_POKEMON_FULFILLED';

const CLEAR_LIST = 'CLEAR_LIST'
const CLEAR_POKEMON='CLEAR_POKEMON'

export {
    GET_POKEMON_LIST,
    GET_POKEMON_LIST_FULFILLED,
    GET_POKEMON_LIST_PENDING,
    GET_POKEMON_LIST_REJECTED,
    CLEAR_LIST,
    GET_POKEMON,
    GET_POKEMON_PENDING,
    GET_POKEMON_REJECTED,
    GET_POKEMON_FULFILLED,
    CLEAR_POKEMON
}